### ISSUE TITLE
Suggestion - RandomChanceProcessor for stairs and other state-based blocks

### ISSUE THREAD

**Issue by Draylar** [kvverti/structure-helpers#4]
`RandomChanceProcessor` works fantastically, but is a bit of a pain to use for stairs, slabs, and other blocks that have states (like direction). What would be awesome is a chance processor that would let me ignore the specifics of the state, and just replace the type of block, like so:
```java
RandomChanceProcessor
    .builder()
    .add(Blocks.STONE_BRICK_STAIRS, RandomChanceProcessor.Entry.of(Blocks.SANDSTONE_STAIRS, 1))
    .build()
```
This would replace _any_ stone brick stairs with sandstone stairs, keeping the same direction.

**Comment by kvverti** [comment]
Implemented :)
